{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "582fa573-0f51-4924-a5ab-30d6bcac9e7f",
   "metadata": {},
   "source": [
    "<h3> Company Wise EV Vehicle Data from 2019-2024 </h3>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "id": "f93386d0-cb67-4ce8-8ca9-096b96312349",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Company                0\n",
      "Vehicle Type           1\n",
      "2019 Sales (Units)     0\n",
      "2020 Sales (Units)     0\n",
      "2021 Sales (Units)     0\n",
      "2022 Sales (Units)     0\n",
      "2023 Sales (Units)     0\n",
      "2024 Sales (Units)     0\n",
      "Growth Trend           0\n",
      "Market Share %         0\n",
      "Manufacturing State    0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df=pd.read_csv(\"C:\\\\Users\\\\srava\\\\OneDrive\\\\Desktop\\\\2019-2024  EVs Comapy Wise.csv\")\n",
    "\n",
    "print(df.isnull().sum())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "7ebe25a9-002f-450d-b655-72a68b13aca9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\srava\\AppData\\Local\\Temp\\ipykernel_11780\\937949306.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  df['Vehicle Type'].fillna('Unknown', inplace=True)\n"
     ]
    }
   ],
   "source": [
    "df['Vehicle Type'].fillna('Unknown', inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "id": "3b78e618-fe25-41a6-ba0f-adf7e12957f9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Company</th>\n",
       "      <th>Vehicle Type</th>\n",
       "      <th>2019 Sales (Units)</th>\n",
       "      <th>2020 Sales (Units)</th>\n",
       "      <th>2021 Sales (Units)</th>\n",
       "      <th>2022 Sales (Units)</th>\n",
       "      <th>2023 Sales (Units)</th>\n",
       "      <th>2024 Sales (Units)</th>\n",
       "      <th>Growth Trend</th>\n",
       "      <th>Market Share %</th>\n",
       "      <th>Manufacturing State</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Tata Motors</td>\n",
       "      <td>Cars</td>\n",
       "      <td>2000</td>\n",
       "      <td>2500</td>\n",
       "      <td>5000</td>\n",
       "      <td>35000</td>\n",
       "      <td>70000</td>\n",
       "      <td>95000</td>\n",
       "      <td>High</td>\n",
       "      <td>70%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Mahindra Electric</td>\n",
       "      <td>Cars</td>\n",
       "      <td>500</td>\n",
       "      <td>600</td>\n",
       "      <td>1000</td>\n",
       "      <td>3000</td>\n",
       "      <td>10000</td>\n",
       "      <td>20000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>10%</td>\n",
       "      <td>Karnataka</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Ather Energy</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>1500</td>\n",
       "      <td>2000</td>\n",
       "      <td>15000</td>\n",
       "      <td>50000</td>\n",
       "      <td>90000</td>\n",
       "      <td>120000</td>\n",
       "      <td>High</td>\n",
       "      <td>8%</td>\n",
       "      <td>Karnataka</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Hero Electric</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>50000</td>\n",
       "      <td>55000</td>\n",
       "      <td>65000</td>\n",
       "      <td>100000</td>\n",
       "      <td>100000</td>\n",
       "      <td>80000</td>\n",
       "      <td>Varied</td>\n",
       "      <td>10%</td>\n",
       "      <td>Delhi</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Ola Electric</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "      <td>100000</td>\n",
       "      <td>250000</td>\n",
       "      <td>400000</td>\n",
       "      <td>Very High</td>\n",
       "      <td>35%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Ashok Leyland (EV Bus)</td>\n",
       "      <td>Electric Buses</td>\n",
       "      <td>50</td>\n",
       "      <td>75</td>\n",
       "      <td>100</td>\n",
       "      <td>200</td>\n",
       "      <td>500</td>\n",
       "      <td>1000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>20%</td>\n",
       "      <td>Rajasthan</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>TVS Motor Company</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>1000</td>\n",
       "      <td>1500</td>\n",
       "      <td>5000</td>\n",
       "      <td>20000</td>\n",
       "      <td>100000</td>\n",
       "      <td>150000</td>\n",
       "      <td>High</td>\n",
       "      <td>7%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Bajaj Auto (EV)</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>500</td>\n",
       "      <td>750</td>\n",
       "      <td>2000</td>\n",
       "      <td>15000</td>\n",
       "      <td>80000</td>\n",
       "      <td>120000</td>\n",
       "      <td>High</td>\n",
       "      <td>6%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>MG Motor India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "      <td>3000</td>\n",
       "      <td>5000</td>\n",
       "      <td>8000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>1%</td>\n",
       "      <td>Gujarat</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Hyundai Motor India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>500</td>\n",
       "      <td>2000</td>\n",
       "      <td>5000</td>\n",
       "      <td>10000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.50%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Revolt Motors</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>500</td>\n",
       "      <td>1000</td>\n",
       "      <td>5000</td>\n",
       "      <td>10000</td>\n",
       "      <td>5000</td>\n",
       "      <td>8000</td>\n",
       "      <td>Varied</td>\n",
       "      <td>0.10%</td>\n",
       "      <td>Haryana</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Ampere Vehicles</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>10000</td>\n",
       "      <td>12000</td>\n",
       "      <td>20000</td>\n",
       "      <td>40000</td>\n",
       "      <td>50000</td>\n",
       "      <td>60000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>4%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Okinawa Autotech</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>15000</td>\n",
       "      <td>20000</td>\n",
       "      <td>30000</td>\n",
       "      <td>90000</td>\n",
       "      <td>80000</td>\n",
       "      <td>70000</td>\n",
       "      <td>Varied</td>\n",
       "      <td>6%</td>\n",
       "      <td>Rajasthan</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Kinetic Green Energy (3-Wheelers)</td>\n",
       "      <td>3-Wheelers</td>\n",
       "      <td>2000</td>\n",
       "      <td>3000</td>\n",
       "      <td>8000</td>\n",
       "      <td>20000</td>\n",
       "      <td>30000</td>\n",
       "      <td>40000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>8%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>BYD India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>100</td>\n",
       "      <td>150</td>\n",
       "      <td>300</td>\n",
       "      <td>1500</td>\n",
       "      <td>2000</td>\n",
       "      <td>2500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.10%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>JBM Auto</td>\n",
       "      <td>Electric Buses</td>\n",
       "      <td>20</td>\n",
       "      <td>30</td>\n",
       "      <td>50</td>\n",
       "      <td>150</td>\n",
       "      <td>300</td>\n",
       "      <td>500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>5%</td>\n",
       "      <td>Haryana</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Piaggio Vehicles</td>\n",
       "      <td>3-Wheelers</td>\n",
       "      <td>200</td>\n",
       "      <td>300</td>\n",
       "      <td>800</td>\n",
       "      <td>3000</td>\n",
       "      <td>8000</td>\n",
       "      <td>15000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>3%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Hero MotoCorp</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "      <td>10000</td>\n",
       "      <td>50000</td>\n",
       "      <td>Rapidly Increasing</td>\n",
       "      <td>0.50%</td>\n",
       "      <td>Haryana</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Etrio Automobiles</td>\n",
       "      <td>3-Wheelers</td>\n",
       "      <td>50</td>\n",
       "      <td>100</td>\n",
       "      <td>300</td>\n",
       "      <td>1000</td>\n",
       "      <td>2000</td>\n",
       "      <td>3000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.10%</td>\n",
       "      <td>Telangana</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Triton Electric</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50</td>\n",
       "      <td>200</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>Gujarat</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Simple Energy</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>100</td>\n",
       "      <td>1000</td>\n",
       "      <td>5000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.05%</td>\n",
       "      <td>Karnataka</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Greaves Cotton/Greaves Electric Mobility</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>5000</td>\n",
       "      <td>7000</td>\n",
       "      <td>15000</td>\n",
       "      <td>30000</td>\n",
       "      <td>35000</td>\n",
       "      <td>40000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>3%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Maruti Suzuki India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>5000</td>\n",
       "      <td>Very New</td>\n",
       "      <td>0.10%</td>\n",
       "      <td>Haryana</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Renault India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>200</td>\n",
       "      <td>1000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.01%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Citroën India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>100</td>\n",
       "      <td>500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.01%</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Audi India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50</td>\n",
       "      <td>200</td>\n",
       "      <td>500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.01%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Mercedes-Benz India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>100</td>\n",
       "      <td>400</td>\n",
       "      <td>800</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.02%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Kia Motors India</td>\n",
       "      <td>Cars</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50</td>\n",
       "      <td>300</td>\n",
       "      <td>1000</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.05%</td>\n",
       "      <td>Andhra Pradesh</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Volvo Eicher</td>\n",
       "      <td>Commercial Vehicles</td>\n",
       "      <td>50</td>\n",
       "      <td>75</td>\n",
       "      <td>100</td>\n",
       "      <td>200</td>\n",
       "      <td>400</td>\n",
       "      <td>700</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.10%</td>\n",
       "      <td>Madhya Pradesh</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>Olectra Greentech</td>\n",
       "      <td>Electric Buses</td>\n",
       "      <td>20</td>\n",
       "      <td>30</td>\n",
       "      <td>50</td>\n",
       "      <td>100</td>\n",
       "      <td>200</td>\n",
       "      <td>400</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>3%</td>\n",
       "      <td>Telangana</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>Force Motors</td>\n",
       "      <td>EV Vans</td>\n",
       "      <td>100</td>\n",
       "      <td>150</td>\n",
       "      <td>300</td>\n",
       "      <td>800</td>\n",
       "      <td>1500</td>\n",
       "      <td>2500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.10%</td>\n",
       "      <td>Maharashtra</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>Atul Auto</td>\n",
       "      <td>3-Wheelers</td>\n",
       "      <td>100</td>\n",
       "      <td>150</td>\n",
       "      <td>300</td>\n",
       "      <td>800</td>\n",
       "      <td>1500</td>\n",
       "      <td>2500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.50%</td>\n",
       "      <td>Gujarat</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>SML Isuzu</td>\n",
       "      <td>Commercial Vehicles</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>100</td>\n",
       "      <td>500</td>\n",
       "      <td>Increasing</td>\n",
       "      <td>0.01%</td>\n",
       "      <td>Punjab</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>Mahindra Reva</td>\n",
       "      <td>Unknown</td>\n",
       "      <td>100</td>\n",
       "      <td>150</td>\n",
       "      <td>300</td>\n",
       "      <td>500</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>Decreasing</td>\n",
       "      <td>0</td>\n",
       "      <td>Karnataka</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>HOP Electric Mobility</td>\n",
       "      <td>2-Wheelers</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>500</td>\n",
       "      <td>5000</td>\n",
       "      <td>15000</td>\n",
       "      <td>30000</td>\n",
       "      <td>Rapidly Increasing</td>\n",
       "      <td>1%</td>\n",
       "      <td>Rajasthan</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Omega Seiki Mobility</td>\n",
       "      <td>3-Wheelers</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>200</td>\n",
       "      <td>1000</td>\n",
       "      <td>3000</td>\n",
       "      <td>8000</td>\n",
       "      <td>Rapidly Increasing</td>\n",
       "      <td>0.50%</td>\n",
       "      <td>Haryana</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                     Company         Vehicle Type  \\\n",
       "0                                Tata Motors                 Cars   \n",
       "1                          Mahindra Electric                 Cars   \n",
       "2                               Ather Energy           2-Wheelers   \n",
       "3                              Hero Electric           2-Wheelers   \n",
       "4                               Ola Electric           2-Wheelers   \n",
       "5                     Ashok Leyland (EV Bus)       Electric Buses   \n",
       "6                          TVS Motor Company           2-Wheelers   \n",
       "7                            Bajaj Auto (EV)           2-Wheelers   \n",
       "8                             MG Motor India                 Cars   \n",
       "9                        Hyundai Motor India                 Cars   \n",
       "10                             Revolt Motors           2-Wheelers   \n",
       "11                           Ampere Vehicles           2-Wheelers   \n",
       "12                          Okinawa Autotech           2-Wheelers   \n",
       "13         Kinetic Green Energy (3-Wheelers)           3-Wheelers   \n",
       "14                                 BYD India                 Cars   \n",
       "15                                  JBM Auto       Electric Buses   \n",
       "16                          Piaggio Vehicles           3-Wheelers   \n",
       "17                             Hero MotoCorp           2-Wheelers   \n",
       "18                         Etrio Automobiles           3-Wheelers   \n",
       "19                           Triton Electric                 Cars   \n",
       "20                             Simple Energy           2-Wheelers   \n",
       "21  Greaves Cotton/Greaves Electric Mobility           2-Wheelers   \n",
       "22                       Maruti Suzuki India                 Cars   \n",
       "23                             Renault India                 Cars   \n",
       "24                             Citroën India                 Cars   \n",
       "25                                Audi India                 Cars   \n",
       "26                       Mercedes-Benz India                 Cars   \n",
       "27                          Kia Motors India                 Cars   \n",
       "28                              Volvo Eicher  Commercial Vehicles   \n",
       "29                         Olectra Greentech       Electric Buses   \n",
       "30                              Force Motors              EV Vans   \n",
       "31                                 Atul Auto           3-Wheelers   \n",
       "32                                 SML Isuzu  Commercial Vehicles   \n",
       "33                             Mahindra Reva              Unknown   \n",
       "34                     HOP Electric Mobility           2-Wheelers   \n",
       "35                      Omega Seiki Mobility           3-Wheelers   \n",
       "\n",
       "    2019 Sales (Units)  2020 Sales (Units)  2021 Sales (Units)  \\\n",
       "0                 2000                2500                5000   \n",
       "1                  500                 600                1000   \n",
       "2                 1500                2000               15000   \n",
       "3                50000               55000               65000   \n",
       "4                    0                   0                1000   \n",
       "5                   50                  75                 100   \n",
       "6                 1000                1500                5000   \n",
       "7                  500                 750                2000   \n",
       "8                    0                   0                1000   \n",
       "9                    0                   0                 500   \n",
       "10                 500                1000                5000   \n",
       "11               10000               12000               20000   \n",
       "12               15000               20000               30000   \n",
       "13                2000                3000                8000   \n",
       "14                 100                 150                 300   \n",
       "15                  20                  30                  50   \n",
       "16                 200                 300                 800   \n",
       "17                   0                   0                   0   \n",
       "18                  50                 100                 300   \n",
       "19                   0                   0                   0   \n",
       "20                   0                   0                   0   \n",
       "21                5000                7000               15000   \n",
       "22                   0                   0                   0   \n",
       "23                   0                   0                   0   \n",
       "24                   0                   0                   0   \n",
       "25                   0                   0                   0   \n",
       "26                   0                   0                   0   \n",
       "27                   0                   0                   0   \n",
       "28                  50                  75                 100   \n",
       "29                  20                  30                  50   \n",
       "30                 100                 150                 300   \n",
       "31                 100                 150                 300   \n",
       "32                   0                   0                   0   \n",
       "33                 100                 150                 300   \n",
       "34                   0                   0                 500   \n",
       "35                   0                   0                 200   \n",
       "\n",
       "    2022 Sales (Units)  2023 Sales (Units)  2024 Sales (Units)  \\\n",
       "0                35000               70000               95000   \n",
       "1                 3000               10000               20000   \n",
       "2                50000               90000              120000   \n",
       "3               100000              100000               80000   \n",
       "4               100000              250000              400000   \n",
       "5                  200                 500                1000   \n",
       "6                20000              100000              150000   \n",
       "7                15000               80000              120000   \n",
       "8                 3000                5000                8000   \n",
       "9                 2000                5000               10000   \n",
       "10               10000                5000                8000   \n",
       "11               40000               50000               60000   \n",
       "12               90000               80000               70000   \n",
       "13               20000               30000               40000   \n",
       "14                1500                2000                2500   \n",
       "15                 150                 300                 500   \n",
       "16                3000                8000               15000   \n",
       "17                1000               10000               50000   \n",
       "18                1000                2000                3000   \n",
       "19                   0                  50                 200   \n",
       "20                 100                1000                5000   \n",
       "21               30000               35000               40000   \n",
       "22                   0                   0                5000   \n",
       "23                   0                 200                1000   \n",
       "24                   0                 100                 500   \n",
       "25                  50                 200                 500   \n",
       "26                 100                 400                 800   \n",
       "27                  50                 300                1000   \n",
       "28                 200                 400                 700   \n",
       "29                 100                 200                 400   \n",
       "30                 800                1500                2500   \n",
       "31                 800                1500                2500   \n",
       "32                   0                 100                 500   \n",
       "33                 500                   0                   0   \n",
       "34                5000               15000               30000   \n",
       "35                1000                3000                8000   \n",
       "\n",
       "          Growth Trend Market Share % Manufacturing State  \n",
       "0                 High            70%         Maharashtra  \n",
       "1           Increasing            10%           Karnataka  \n",
       "2                 High             8%           Karnataka  \n",
       "3               Varied            10%               Delhi  \n",
       "4            Very High            35%          Tamil Nadu  \n",
       "5           Increasing            20%           Rajasthan  \n",
       "6                 High             7%          Tamil Nadu  \n",
       "7                 High             6%         Maharashtra  \n",
       "8           Increasing             1%             Gujarat  \n",
       "9           Increasing          0.50%          Tamil Nadu  \n",
       "10              Varied          0.10%             Haryana  \n",
       "11          Increasing             4%          Tamil Nadu  \n",
       "12              Varied             6%           Rajasthan  \n",
       "13          Increasing             8%         Maharashtra  \n",
       "14          Increasing          0.10%          Tamil Nadu  \n",
       "15          Increasing             5%             Haryana  \n",
       "16          Increasing             3%         Maharashtra  \n",
       "17  Rapidly Increasing          0.50%             Haryana  \n",
       "18          Increasing          0.10%           Telangana  \n",
       "19          Increasing          0.00%             Gujarat  \n",
       "20          Increasing          0.05%           Karnataka  \n",
       "21          Increasing             3%         Maharashtra  \n",
       "22            Very New          0.10%             Haryana  \n",
       "23          Increasing          0.01%          Tamil Nadu  \n",
       "24          Increasing          0.01%          Tamil Nadu  \n",
       "25          Increasing          0.01%         Maharashtra  \n",
       "26          Increasing          0.02%         Maharashtra  \n",
       "27          Increasing          0.05%      Andhra Pradesh  \n",
       "28          Increasing          0.10%      Madhya Pradesh  \n",
       "29          Increasing             3%           Telangana  \n",
       "30          Increasing          0.10%         Maharashtra  \n",
       "31          Increasing          0.50%             Gujarat  \n",
       "32          Increasing          0.01%              Punjab  \n",
       "33          Decreasing              0           Karnataka  \n",
       "34  Rapidly Increasing             1%           Rajasthan  \n",
       "35  Rapidly Increasing          0.50%             Haryana  "
      ]
     },
     "execution_count": 105,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "id": "6e77814e-0b8f-44d7-8814-7beaed4f5663",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop_duplicates(inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "id": "aee0eae1-6448-4420-926d-65fb7e541c6b",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv(\"C:\\\\Users\\\\srava\\\\OneDrive\\\\Desktop\\\\Cleanded2019-2024EVsComapyWiseData.csv\", index=False) "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "483d59a4-c809-420f-9aa8-bbedcbcde6f3",
   "metadata": {},
   "source": [
    "<h3> Total Vehicles VS EV Vehicles Data</h3>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 112,
   "id": "36d9ee77-9f12-4757-8620-32ac0ac361e9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sl. No.</th>\n",
       "      <th>State/ UT</th>\n",
       "      <th>Total EV</th>\n",
       "      <th>Total Vehicles Sold</th>\n",
       "      <th>% of Share of EV in Total Vehicles Sold</th>\n",
       "      <th>Unnamed: 5</th>\n",
       "      <th>Unnamed: 6</th>\n",
       "      <th>Unnamed: 7</th>\n",
       "      <th>No of Charging Stations</th>\n",
       "      <th>Unnamed: 9</th>\n",
       "      <th>Unnamed: 10</th>\n",
       "      <th>Unnamed: 11</th>\n",
       "      <th>Unnamed: 12</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Andaman and Nicobar Islands</td>\n",
       "      <td>191</td>\n",
       "      <td>35896</td>\n",
       "      <td>0.53</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Andhra Pradesh</td>\n",
       "      <td>88534</td>\n",
       "      <td>4772995</td>\n",
       "      <td>1.85</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>327</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Arunachal Pradesh</td>\n",
       "      <td>42</td>\n",
       "      <td>137145</td>\n",
       "      <td>0.03</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>9</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Assam</td>\n",
       "      <td>150617</td>\n",
       "      <td>2599986</td>\n",
       "      <td>5.79</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>86</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Bihar</td>\n",
       "      <td>214921</td>\n",
       "      <td>5763437</td>\n",
       "      <td>3.73</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>124</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>6</td>\n",
       "      <td>Chandigarh</td>\n",
       "      <td>12375</td>\n",
       "      <td>219391</td>\n",
       "      <td>5.64</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>12</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>7</td>\n",
       "      <td>Chhattisgarh</td>\n",
       "      <td>80348</td>\n",
       "      <td>2656935</td>\n",
       "      <td>3.02</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>149</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8</td>\n",
       "      <td>Dadra and Nagar Haveli and Daman and Diu</td>\n",
       "      <td>468</td>\n",
       "      <td>90571</td>\n",
       "      <td>0.52</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>9</td>\n",
       "      <td>Delhi</td>\n",
       "      <td>216084</td>\n",
       "      <td>2799571</td>\n",
       "      <td>7.72</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1886</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>10</td>\n",
       "      <td>Goa</td>\n",
       "      <td>20330</td>\n",
       "      <td>323748</td>\n",
       "      <td>6.28</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>113</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>11</td>\n",
       "      <td>Gujarat</td>\n",
       "      <td>191185</td>\n",
       "      <td>7450473</td>\n",
       "      <td>2.57</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>476</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>12</td>\n",
       "      <td>Haryana</td>\n",
       "      <td>81775</td>\n",
       "      <td>3703954</td>\n",
       "      <td>2.21</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>377</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>13</td>\n",
       "      <td>Himachal Pradesh</td>\n",
       "      <td>3043</td>\n",
       "      <td>636556</td>\n",
       "      <td>0.48</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>44</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>14</td>\n",
       "      <td>Jammu and Kashmir</td>\n",
       "      <td>19099</td>\n",
       "      <td>823164</td>\n",
       "      <td>2.32</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>47</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>15</td>\n",
       "      <td>Jharkhand</td>\n",
       "      <td>47400</td>\n",
       "      <td>2545053</td>\n",
       "      <td>1.86</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>135</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>16</td>\n",
       "      <td>Karnataka</td>\n",
       "      <td>350810</td>\n",
       "      <td>7315250</td>\n",
       "      <td>4.80</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>17</td>\n",
       "      <td>Kerala</td>\n",
       "      <td>151029</td>\n",
       "      <td>3781393</td>\n",
       "      <td>3.99</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>852</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>18</td>\n",
       "      <td>Ladakh</td>\n",
       "      <td>88</td>\n",
       "      <td>19645</td>\n",
       "      <td>0.45</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>11</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>19</td>\n",
       "      <td>Lakshadweep</td>\n",
       "      <td>19</td>\n",
       "      <td>2752</td>\n",
       "      <td>0.69</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>20</td>\n",
       "      <td>Madhya Pradesh</td>\n",
       "      <td>144782</td>\n",
       "      <td>6812437</td>\n",
       "      <td>2.13</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>341</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>21</td>\n",
       "      <td>Maharashtra</td>\n",
       "      <td>439358</td>\n",
       "      <td>11055082</td>\n",
       "      <td>3.97</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>3079</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>22</td>\n",
       "      <td>Manipur</td>\n",
       "      <td>1273</td>\n",
       "      <td>168310</td>\n",
       "      <td>0.76</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>17</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>23</td>\n",
       "      <td>Meghalaya</td>\n",
       "      <td>572</td>\n",
       "      <td>162249</td>\n",
       "      <td>0.35</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>21</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>24</td>\n",
       "      <td>Mizoram</td>\n",
       "      <td>344</td>\n",
       "      <td>136845</td>\n",
       "      <td>0.25</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>13</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>25</td>\n",
       "      <td>Nagaland</td>\n",
       "      <td>27</td>\n",
       "      <td>119281</td>\n",
       "      <td>0.02</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>6</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>26</td>\n",
       "      <td>Odisha</td>\n",
       "      <td>97056</td>\n",
       "      <td>3355237</td>\n",
       "      <td>2.89</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>198</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>27</td>\n",
       "      <td>Puducherry</td>\n",
       "      <td>5933</td>\n",
       "      <td>252488</td>\n",
       "      <td>2.35</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>23</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>28</td>\n",
       "      <td>Punjab</td>\n",
       "      <td>56459</td>\n",
       "      <td>2973281</td>\n",
       "      <td>1.90</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>158</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>29</td>\n",
       "      <td>Rajasthan</td>\n",
       "      <td>233503</td>\n",
       "      <td>6490725</td>\n",
       "      <td>3.60</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>500</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>30</td>\n",
       "      <td>Sikkim</td>\n",
       "      <td>20</td>\n",
       "      <td>49884</td>\n",
       "      <td>0.04</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>31</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "      <td>228850</td>\n",
       "      <td>8476042</td>\n",
       "      <td>2.70</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>643</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>32</td>\n",
       "      <td>Telangana</td>\n",
       "      <td>35000</td>\n",
       "      <td>17231633</td>\n",
       "      <td>0.20</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>481</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>33</td>\n",
       "      <td>Tripura</td>\n",
       "      <td>20113</td>\n",
       "      <td>264004</td>\n",
       "      <td>7.62</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>18</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>34</td>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>665247</td>\n",
       "      <td>15317699</td>\n",
       "      <td>4.34</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>582</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>35</td>\n",
       "      <td>Uttarakhand</td>\n",
       "      <td>48522</td>\n",
       "      <td>1120010</td>\n",
       "      <td>4.33</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>76</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>36</td>\n",
       "      <td>West Bengal</td>\n",
       "      <td>69220</td>\n",
       "      <td>5099551</td>\n",
       "      <td>1.36</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>318</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Sl. No.                                 State/ UT  Total EV  \\\n",
       "0         1               Andaman and Nicobar Islands       191   \n",
       "1         2                            Andhra Pradesh     88534   \n",
       "2         3                         Arunachal Pradesh        42   \n",
       "3         4                                     Assam    150617   \n",
       "4         5                                     Bihar    214921   \n",
       "5         6                                Chandigarh     12375   \n",
       "6         7                              Chhattisgarh     80348   \n",
       "7         8  Dadra and Nagar Haveli and Daman and Diu       468   \n",
       "8         9                                     Delhi    216084   \n",
       "9        10                                       Goa     20330   \n",
       "10       11                                   Gujarat    191185   \n",
       "11       12                                   Haryana     81775   \n",
       "12       13                          Himachal Pradesh      3043   \n",
       "13       14                         Jammu and Kashmir     19099   \n",
       "14       15                                 Jharkhand     47400   \n",
       "15       16                                 Karnataka    350810   \n",
       "16       17                                    Kerala    151029   \n",
       "17       18                                    Ladakh        88   \n",
       "18       19                               Lakshadweep        19   \n",
       "19       20                            Madhya Pradesh    144782   \n",
       "20       21                               Maharashtra    439358   \n",
       "21       22                                   Manipur      1273   \n",
       "22       23                                 Meghalaya       572   \n",
       "23       24                                   Mizoram       344   \n",
       "24       25                                  Nagaland        27   \n",
       "25       26                                    Odisha     97056   \n",
       "26       27                                Puducherry      5933   \n",
       "27       28                                    Punjab     56459   \n",
       "28       29                                 Rajasthan    233503   \n",
       "29       30                                    Sikkim        20   \n",
       "30       31                                Tamil Nadu    228850   \n",
       "31       32                                 Telangana     35000   \n",
       "32       33                                   Tripura     20113   \n",
       "33       34                             Uttar Pradesh    665247   \n",
       "34       35                               Uttarakhand     48522   \n",
       "35       36                               West Bengal     69220   \n",
       "\n",
       "    Total Vehicles Sold  % of Share of EV in Total Vehicles Sold  Unnamed: 5  \\\n",
       "0                 35896                                     0.53         NaN   \n",
       "1               4772995                                     1.85         NaN   \n",
       "2                137145                                     0.03         NaN   \n",
       "3               2599986                                     5.79         NaN   \n",
       "4               5763437                                     3.73         NaN   \n",
       "5                219391                                     5.64         NaN   \n",
       "6               2656935                                     3.02         NaN   \n",
       "7                 90571                                     0.52         NaN   \n",
       "8               2799571                                     7.72         NaN   \n",
       "9                323748                                     6.28         NaN   \n",
       "10              7450473                                     2.57         NaN   \n",
       "11              3703954                                     2.21         NaN   \n",
       "12               636556                                     0.48         NaN   \n",
       "13               823164                                     2.32         NaN   \n",
       "14              2545053                                     1.86         NaN   \n",
       "15              7315250                                     4.80         NaN   \n",
       "16              3781393                                     3.99         NaN   \n",
       "17                19645                                     0.45         NaN   \n",
       "18                 2752                                     0.69         NaN   \n",
       "19              6812437                                     2.13         NaN   \n",
       "20             11055082                                     3.97         NaN   \n",
       "21               168310                                     0.76         NaN   \n",
       "22               162249                                     0.35         NaN   \n",
       "23               136845                                     0.25         NaN   \n",
       "24               119281                                     0.02         NaN   \n",
       "25              3355237                                     2.89         NaN   \n",
       "26               252488                                     2.35         NaN   \n",
       "27              2973281                                     1.90         NaN   \n",
       "28              6490725                                     3.60         NaN   \n",
       "29                49884                                     0.04         NaN   \n",
       "30              8476042                                     2.70         NaN   \n",
       "31             17231633                                     0.20         NaN   \n",
       "32               264004                                     7.62         NaN   \n",
       "33             15317699                                     4.34         NaN   \n",
       "34              1120010                                     4.33         NaN   \n",
       "35              5099551                                     1.36         NaN   \n",
       "\n",
       "    Unnamed: 6  Unnamed: 7  No of Charging Stations  Unnamed: 9  Unnamed: 10  \\\n",
       "0          NaN         NaN                        3         NaN          NaN   \n",
       "1          NaN         NaN                      327         NaN          NaN   \n",
       "2          NaN         NaN                        9         NaN          NaN   \n",
       "3          NaN         NaN                       86         NaN          NaN   \n",
       "4          NaN         NaN                      124         NaN          NaN   \n",
       "5          NaN         NaN                       12         NaN          NaN   \n",
       "6          NaN         NaN                      149         NaN          NaN   \n",
       "7          NaN         NaN                        1         NaN          NaN   \n",
       "8          NaN         NaN                     1886         NaN          NaN   \n",
       "9          NaN         NaN                      113         NaN          NaN   \n",
       "10         NaN         NaN                      476         NaN          NaN   \n",
       "11         NaN         NaN                      377         NaN          NaN   \n",
       "12         NaN         NaN                       44         NaN          NaN   \n",
       "13         NaN         NaN                       47         NaN          NaN   \n",
       "14         NaN         NaN                      135         NaN          NaN   \n",
       "15         NaN         NaN                     1041         NaN          NaN   \n",
       "16         NaN         NaN                      852         NaN          NaN   \n",
       "17         NaN         NaN                       11         NaN          NaN   \n",
       "18         NaN         NaN                        1         NaN          NaN   \n",
       "19         NaN         NaN                      341         NaN          NaN   \n",
       "20         NaN         NaN                     3079         NaN          NaN   \n",
       "21         NaN         NaN                       17         NaN          NaN   \n",
       "22         NaN         NaN                       21         NaN          NaN   \n",
       "23         NaN         NaN                       13         NaN          NaN   \n",
       "24         NaN         NaN                        6         NaN          NaN   \n",
       "25         NaN         NaN                      198         NaN          NaN   \n",
       "26         NaN         NaN                       23         NaN          NaN   \n",
       "27         NaN         NaN                      158         NaN          NaN   \n",
       "28         NaN         NaN                      500         NaN          NaN   \n",
       "29         NaN         NaN                        2         NaN          NaN   \n",
       "30         NaN         NaN                      643         NaN          NaN   \n",
       "31         NaN         NaN                      481         NaN          NaN   \n",
       "32         NaN         NaN                       18         NaN          NaN   \n",
       "33         NaN         NaN                      582         NaN          NaN   \n",
       "34         NaN         NaN                       76         NaN          NaN   \n",
       "35         NaN         NaN                      318         NaN          NaN   \n",
       "\n",
       "    Unnamed: 11  Unnamed: 12  \n",
       "0           NaN          NaN  \n",
       "1           NaN          NaN  \n",
       "2           NaN          NaN  \n",
       "3           NaN          NaN  \n",
       "4           NaN          NaN  \n",
       "5           NaN          NaN  \n",
       "6           NaN          NaN  \n",
       "7           NaN          NaN  \n",
       "8           NaN          NaN  \n",
       "9           NaN          NaN  \n",
       "10          NaN          NaN  \n",
       "11          NaN          NaN  \n",
       "12          NaN          NaN  \n",
       "13          NaN          NaN  \n",
       "14          NaN          NaN  \n",
       "15          NaN          NaN  \n",
       "16          NaN          NaN  \n",
       "17          NaN          NaN  \n",
       "18          NaN          NaN  \n",
       "19          NaN          NaN  \n",
       "20          NaN          NaN  \n",
       "21          NaN          NaN  \n",
       "22          NaN          NaN  \n",
       "23          NaN          NaN  \n",
       "24          NaN          NaN  \n",
       "25          NaN          NaN  \n",
       "26          NaN          NaN  \n",
       "27          NaN          NaN  \n",
       "28          NaN          NaN  \n",
       "29          NaN          NaN  \n",
       "30          NaN          NaN  \n",
       "31          NaN          NaN  \n",
       "32          NaN          NaN  \n",
       "33          NaN          NaN  \n",
       "34          NaN          NaN  \n",
       "35          NaN          NaN  "
      ]
     },
     "execution_count": 112,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df = pd.read_csv(\"C:\\\\Users\\\\srava\\\\OneDrive\\\\Desktop\\\\Total EVs.csv\")\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "id": "aa507314-6883-46c3-9725-a97303bf3b0f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Dropping Unwanted Columns\n",
    "df=df.drop(columns=['Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "id": "cfb20a1b-6f2e-4542-85c0-d6f9fe79a680",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sl. No.                                    0\n",
      "State/ UT                                  0\n",
      "Total EV                                   0\n",
      "Total Vehicles Sold                        0\n",
      "% of Share of EV in Total Vehicles Sold    0\n",
      "No of Charging Stations                    0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "#Checking any columns with null values\n",
    "print(df.isnull().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "id": "eb276f50-02ed-490a-a46e-8ff8c5ace118",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sl. No.</th>\n",
       "      <th>State/ UT</th>\n",
       "      <th>Total EV</th>\n",
       "      <th>Total Vehicles Sold</th>\n",
       "      <th>% of Share of EV in Total Vehicles Sold</th>\n",
       "      <th>No of Charging Stations</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Andaman and Nicobar Islands</td>\n",
       "      <td>191</td>\n",
       "      <td>35896</td>\n",
       "      <td>0.53</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Andhra Pradesh</td>\n",
       "      <td>88534</td>\n",
       "      <td>4772995</td>\n",
       "      <td>1.85</td>\n",
       "      <td>327</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Arunachal Pradesh</td>\n",
       "      <td>42</td>\n",
       "      <td>137145</td>\n",
       "      <td>0.03</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Assam</td>\n",
       "      <td>150617</td>\n",
       "      <td>2599986</td>\n",
       "      <td>5.79</td>\n",
       "      <td>86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Bihar</td>\n",
       "      <td>214921</td>\n",
       "      <td>5763437</td>\n",
       "      <td>3.73</td>\n",
       "      <td>124</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>6</td>\n",
       "      <td>Chandigarh</td>\n",
       "      <td>12375</td>\n",
       "      <td>219391</td>\n",
       "      <td>5.64</td>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>7</td>\n",
       "      <td>Chhattisgarh</td>\n",
       "      <td>80348</td>\n",
       "      <td>2656935</td>\n",
       "      <td>3.02</td>\n",
       "      <td>149</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8</td>\n",
       "      <td>Dadra and Nagar Haveli and Daman and Diu</td>\n",
       "      <td>468</td>\n",
       "      <td>90571</td>\n",
       "      <td>0.52</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>9</td>\n",
       "      <td>Delhi</td>\n",
       "      <td>216084</td>\n",
       "      <td>2799571</td>\n",
       "      <td>7.72</td>\n",
       "      <td>1886</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>10</td>\n",
       "      <td>Goa</td>\n",
       "      <td>20330</td>\n",
       "      <td>323748</td>\n",
       "      <td>6.28</td>\n",
       "      <td>113</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>11</td>\n",
       "      <td>Gujarat</td>\n",
       "      <td>191185</td>\n",
       "      <td>7450473</td>\n",
       "      <td>2.57</td>\n",
       "      <td>476</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>12</td>\n",
       "      <td>Haryana</td>\n",
       "      <td>81775</td>\n",
       "      <td>3703954</td>\n",
       "      <td>2.21</td>\n",
       "      <td>377</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>13</td>\n",
       "      <td>Himachal Pradesh</td>\n",
       "      <td>3043</td>\n",
       "      <td>636556</td>\n",
       "      <td>0.48</td>\n",
       "      <td>44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>14</td>\n",
       "      <td>Jammu and Kashmir</td>\n",
       "      <td>19099</td>\n",
       "      <td>823164</td>\n",
       "      <td>2.32</td>\n",
       "      <td>47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>15</td>\n",
       "      <td>Jharkhand</td>\n",
       "      <td>47400</td>\n",
       "      <td>2545053</td>\n",
       "      <td>1.86</td>\n",
       "      <td>135</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>16</td>\n",
       "      <td>Karnataka</td>\n",
       "      <td>350810</td>\n",
       "      <td>7315250</td>\n",
       "      <td>4.80</td>\n",
       "      <td>1041</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>17</td>\n",
       "      <td>Kerala</td>\n",
       "      <td>151029</td>\n",
       "      <td>3781393</td>\n",
       "      <td>3.99</td>\n",
       "      <td>852</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>18</td>\n",
       "      <td>Ladakh</td>\n",
       "      <td>88</td>\n",
       "      <td>19645</td>\n",
       "      <td>0.45</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>19</td>\n",
       "      <td>Lakshadweep</td>\n",
       "      <td>19</td>\n",
       "      <td>2752</td>\n",
       "      <td>0.69</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>20</td>\n",
       "      <td>Madhya Pradesh</td>\n",
       "      <td>144782</td>\n",
       "      <td>6812437</td>\n",
       "      <td>2.13</td>\n",
       "      <td>341</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>21</td>\n",
       "      <td>Maharashtra</td>\n",
       "      <td>439358</td>\n",
       "      <td>11055082</td>\n",
       "      <td>3.97</td>\n",
       "      <td>3079</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>22</td>\n",
       "      <td>Manipur</td>\n",
       "      <td>1273</td>\n",
       "      <td>168310</td>\n",
       "      <td>0.76</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>23</td>\n",
       "      <td>Meghalaya</td>\n",
       "      <td>572</td>\n",
       "      <td>162249</td>\n",
       "      <td>0.35</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>24</td>\n",
       "      <td>Mizoram</td>\n",
       "      <td>344</td>\n",
       "      <td>136845</td>\n",
       "      <td>0.25</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>25</td>\n",
       "      <td>Nagaland</td>\n",
       "      <td>27</td>\n",
       "      <td>119281</td>\n",
       "      <td>0.02</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>26</td>\n",
       "      <td>Odisha</td>\n",
       "      <td>97056</td>\n",
       "      <td>3355237</td>\n",
       "      <td>2.89</td>\n",
       "      <td>198</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>27</td>\n",
       "      <td>Puducherry</td>\n",
       "      <td>5933</td>\n",
       "      <td>252488</td>\n",
       "      <td>2.35</td>\n",
       "      <td>23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>28</td>\n",
       "      <td>Punjab</td>\n",
       "      <td>56459</td>\n",
       "      <td>2973281</td>\n",
       "      <td>1.90</td>\n",
       "      <td>158</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>29</td>\n",
       "      <td>Rajasthan</td>\n",
       "      <td>233503</td>\n",
       "      <td>6490725</td>\n",
       "      <td>3.60</td>\n",
       "      <td>500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>30</td>\n",
       "      <td>Sikkim</td>\n",
       "      <td>20</td>\n",
       "      <td>49884</td>\n",
       "      <td>0.04</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>31</td>\n",
       "      <td>Tamil Nadu</td>\n",
       "      <td>228850</td>\n",
       "      <td>8476042</td>\n",
       "      <td>2.70</td>\n",
       "      <td>643</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>32</td>\n",
       "      <td>Telangana</td>\n",
       "      <td>35000</td>\n",
       "      <td>17231633</td>\n",
       "      <td>0.20</td>\n",
       "      <td>481</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>33</td>\n",
       "      <td>Tripura</td>\n",
       "      <td>20113</td>\n",
       "      <td>264004</td>\n",
       "      <td>7.62</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>34</td>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>665247</td>\n",
       "      <td>15317699</td>\n",
       "      <td>4.34</td>\n",
       "      <td>582</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>35</td>\n",
       "      <td>Uttarakhand</td>\n",
       "      <td>48522</td>\n",
       "      <td>1120010</td>\n",
       "      <td>4.33</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>36</td>\n",
       "      <td>West Bengal</td>\n",
       "      <td>69220</td>\n",
       "      <td>5099551</td>\n",
       "      <td>1.36</td>\n",
       "      <td>318</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Sl. No.                                 State/ UT  Total EV  \\\n",
       "0         1               Andaman and Nicobar Islands       191   \n",
       "1         2                            Andhra Pradesh     88534   \n",
       "2         3                         Arunachal Pradesh        42   \n",
       "3         4                                     Assam    150617   \n",
       "4         5                                     Bihar    214921   \n",
       "5         6                                Chandigarh     12375   \n",
       "6         7                              Chhattisgarh     80348   \n",
       "7         8  Dadra and Nagar Haveli and Daman and Diu       468   \n",
       "8         9                                     Delhi    216084   \n",
       "9        10                                       Goa     20330   \n",
       "10       11                                   Gujarat    191185   \n",
       "11       12                                   Haryana     81775   \n",
       "12       13                          Himachal Pradesh      3043   \n",
       "13       14                         Jammu and Kashmir     19099   \n",
       "14       15                                 Jharkhand     47400   \n",
       "15       16                                 Karnataka    350810   \n",
       "16       17                                    Kerala    151029   \n",
       "17       18                                    Ladakh        88   \n",
       "18       19                               Lakshadweep        19   \n",
       "19       20                            Madhya Pradesh    144782   \n",
       "20       21                               Maharashtra    439358   \n",
       "21       22                                   Manipur      1273   \n",
       "22       23                                 Meghalaya       572   \n",
       "23       24                                   Mizoram       344   \n",
       "24       25                                  Nagaland        27   \n",
       "25       26                                    Odisha     97056   \n",
       "26       27                                Puducherry      5933   \n",
       "27       28                                    Punjab     56459   \n",
       "28       29                                 Rajasthan    233503   \n",
       "29       30                                    Sikkim        20   \n",
       "30       31                                Tamil Nadu    228850   \n",
       "31       32                                 Telangana     35000   \n",
       "32       33                                   Tripura     20113   \n",
       "33       34                             Uttar Pradesh    665247   \n",
       "34       35                               Uttarakhand     48522   \n",
       "35       36                               West Bengal     69220   \n",
       "\n",
       "    Total Vehicles Sold  % of Share of EV in Total Vehicles Sold  \\\n",
       "0                 35896                                     0.53   \n",
       "1               4772995                                     1.85   \n",
       "2                137145                                     0.03   \n",
       "3               2599986                                     5.79   \n",
       "4               5763437                                     3.73   \n",
       "5                219391                                     5.64   \n",
       "6               2656935                                     3.02   \n",
       "7                 90571                                     0.52   \n",
       "8               2799571                                     7.72   \n",
       "9                323748                                     6.28   \n",
       "10              7450473                                     2.57   \n",
       "11              3703954                                     2.21   \n",
       "12               636556                                     0.48   \n",
       "13               823164                                     2.32   \n",
       "14              2545053                                     1.86   \n",
       "15              7315250                                     4.80   \n",
       "16              3781393                                     3.99   \n",
       "17                19645                                     0.45   \n",
       "18                 2752                                     0.69   \n",
       "19              6812437                                     2.13   \n",
       "20             11055082                                     3.97   \n",
       "21               168310                                     0.76   \n",
       "22               162249                                     0.35   \n",
       "23               136845                                     0.25   \n",
       "24               119281                                     0.02   \n",
       "25              3355237                                     2.89   \n",
       "26               252488                                     2.35   \n",
       "27              2973281                                     1.90   \n",
       "28              6490725                                     3.60   \n",
       "29                49884                                     0.04   \n",
       "30              8476042                                     2.70   \n",
       "31             17231633                                     0.20   \n",
       "32               264004                                     7.62   \n",
       "33             15317699                                     4.34   \n",
       "34              1120010                                     4.33   \n",
       "35              5099551                                     1.36   \n",
       "\n",
       "    No of Charging Stations  \n",
       "0                         3  \n",
       "1                       327  \n",
       "2                         9  \n",
       "3                        86  \n",
       "4                       124  \n",
       "5                        12  \n",
       "6                       149  \n",
       "7                         1  \n",
       "8                      1886  \n",
       "9                       113  \n",
       "10                      476  \n",
       "11                      377  \n",
       "12                       44  \n",
       "13                       47  \n",
       "14                      135  \n",
       "15                     1041  \n",
       "16                      852  \n",
       "17                       11  \n",
       "18                        1  \n",
       "19                      341  \n",
       "20                     3079  \n",
       "21                       17  \n",
       "22                       21  \n",
       "23                       13  \n",
       "24                        6  \n",
       "25                      198  \n",
       "26                       23  \n",
       "27                      158  \n",
       "28                      500  \n",
       "29                        2  \n",
       "30                      643  \n",
       "31                      481  \n",
       "32                       18  \n",
       "33                      582  \n",
       "34                       76  \n",
       "35                      318  "
      ]
     },
     "execution_count": 118,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "id": "d6932b7f-36fe-4ae7-98c3-0eb74b5add1b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Saving into CSV file without indices\n",
    "df.to_csv(\"C:\\\\Users\\\\srava\\\\OneDrive\\\\Desktop\\\\EVDetailsCleaned.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e979130e-4247-4f91-94dd-a70ab88b847e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
